### ISSUE TITLE
Public interface to find trains with data for one or more sources

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo_data#112]
`karabo_data_interactive` is currently doing this:

```python
def _find_good_trains(self):
    trains_with_images = {}

    for source_name, source_files in self.run._source_index.items():
        good_trains_source = []
        for file in source_files:
            good_trains_source += \
                set(file.train_ids[file.get_index(source_name, 'image')[1].nonzero()])

        trains_with_images[source_name] = good_trains_source

    self.good_trains_per_source = trains_with_images
    self.good_trains = reduce(np.intersect1d, [v for v in trains_with_images.values()])
```

This uses the private attribute `_source_index`. We should ensure that it can work with only public interfaces.

**Comment by RobertRosca** [comment]
I'm happy with the way `_source_index` works, where it returns a dictionary of source names and files

So would an easy solution be be to just add another attribute, which is equal to `_source_index`, but called something along the lines of: `detector_files`, `source_files`, or `instrument_source_files`?

Not too sure what a good name would be for it would be
