### ISSUE TITLE
get_array() doesn't respect selected trains

### ISSUE THREAD

**Issue by dscran** [European-XFEL/karabo_data#114]

**Comment by dscran** [comment]
Pre-selecting trains by index or trainId has no effect when requesting data arrays or dataframes.

Steps to reproduce:
`run = RunDirectory('/gpfs/exfel/exp/SCS/201802/p002197/raw/r0023/')`
`run.info()`
`sel = run.select_trains(by_index[:10])`
`sel.info()  # correctly shows limited number of trains`
`arr = sel.get_array('SCS_CDIDET_FCCD2M/DAQ/FCCD:daqOutput','data.image.pixels')`
`arr.shape  # shows 500 frames instead of expected 10`

So the selection is expected to be limited to ten trains, but in my case returns 500 trains. The problem is the same for get_dataframe. The info() function on the run selection indicated the correct number of trains.

**Comment by takluyver** [comment]
Thanks, I think this is something that was already fixed in master (pull request #85). I'm working on further improvement in pull request #113, if you have time to take a look.

We should try to make a new release soon. Unfortunately code review is a bit of a bottleneck at the moment.

**Comment by takluyver** [comment]
This should be fixed in 0.3, which was released a few days ago.
