### ISSUE TITLE
Reconsider Python 3.4 support

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo_data#120]
I noticed that the tests take much longer on Python 3.4, because it's building numpy and pyzmq on Travis. It's easy enough to fix that if it's still important, but it's certainly looking like the world is moving on from 3.4.

Does anyone know of a particular use case that requires Python 3.4? If not, let's stop testing on it (and maybe start testing on 3.7 instead).

**Comment by tmichela** [comment]
+1
