### ISSUE TITLE
Failed to run "run.get_array"

### ISSUE THREAD

**Issue by Calpas** [European-XFEL/karabo_data#122]
Dear experts, 
* from the tutorial "Accessing LPD data" (1), when I run (2) I have this error message (3) instead of the output from the tutorial. Do you see what is wrong? 
* please point me to the right forum if here is not the right place for this question.
Regards

(1)
https://karabo-data.readthedocs.io/en/latest/lpd_data.html

(2)
data_module0 = run.get_array('FXE_DET_LPD1M-1/DET/0CH0:xtdf', 'image.data')

(3)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-02a034466132> in <module>()
----> 1 data_module0 = run.get_array('FXE_DET_LPD1M-1/DET/0CH0:xtdf', 'image.data')

/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_data/reader.py in get_array(self, source, key, extra_dims)
    595                 if (counts > 1).any():
    596                     raise ValueError("{}/{} data has more than one data point per train"
--> 597                                      .format(source, group))
    598                 trainids = self._expand_trainids(counts, f.train_ids)
    599 

ValueError: FXE_DET_LPD1M-1/DET/0CH0:xtdf/image data has more than one data point per train

**Comment by takluyver** [comment]
Yep, it's fine to ask here. This was a limitation in karabo_data 0.2, which we lifted in 0.3. You can upgrade with `pip install --upgrade karabo_data` (you may also need the `--user` flag; if you're not sure, try without first, and add `--user` if you see an error about permissions).

**Comment by Calpas** [comment]
Dear Takluyver,
it helps. Thank you.
Regards
