### ISSUE TITLE
unable to open file: name = 'lpd_mar_18_axesfixed.h5'

### ISSUE THREAD

**Issue by Calpas** [European-XFEL/karabo_data#125]
Dear experts,
I tried to access the geometry file with (1) as show in the tutorial, but I got this error message (2). Is this file still available? if not which one should I use?
Regards

(1)
geom = LPD_1MGeometry.from_h5_file_and_quad_positions('lpd_mar_18_axesfixed.h5', quadpos)

(2)
OSError                                   Traceback (most recent call last)
<ipython-input-62-37f7581ca033> in <module>()
      1 # From March 18; converted to XFEL standard coordinate directions
      2 quadpos = [(11.4, 299), (-11.5, 8), (254.5, -16), (278.5, 275)]  # mm
----> 3 geom = LPD_1MGeometry.from_h5_file_and_quad_positions('lpd_mar_18_axesfixed.h5', quadpos)

/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_data/geometry2.py in from_h5_file_and_quad_positions(cls, path, positions, unit)
    906         assert len(positions) == 4
    907         modules = []
--> 908         with h5py.File(path, 'r') as f:
    909             for Q, M in product(range(1, 5), range(1, 5)):
    910                 quad_pos = np.array(positions[Q - 1])

/software/anaconda3/5.2/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

/software/anaconda3/5.2/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     97         if swmr and swmr_support:
     98             flags |= h5f.ACC_SWMR_READ
---> 99         fid = h5f.open(name, flags, fapl=fapl)
    100     elif mode == 'r+':
    101         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'lpd_mar_18_axesfixed.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by takluyver** [comment]
It's available here: https://github.com/European-XFEL/karabo_data/blob/master/docs/lpd_mar_18_axesfixed.h5

N.B. the detector quadrants are moveable, and if supermodules are replaced their relative positions may also shift slightly. The geometry file we have was generated a year ago, and we can't guarantee whether it's still accurate for recent data. Check with the XFEL instrument scientists or detector group if you need accurate geometry.

**Comment by Calpas** [comment]
Thank you. And how should I parse this path to (1). This file should somehow be available in a database I guess?

(1)
geom = LPD_1MGeometry.from_h5_file_and_quad_positions('lpd_mar_18_axesfixed.h5', quadpos)

**Comment by takluyver** [comment]
You have to download the file and put it in the same directory as the script/notebook you're running. Or save it anywhere else and specify a path to it.

Longer term, the geometry is meant to be in a calibration database. These files are an interim solution until that's ready.

**Comment by Calpas** [comment]
It makes sense but when I do that I have this error message?


OSError                                   Traceback (most recent call last)
<ipython-input-14-1515a15f504f> in <module>()
      4 
      5 #geom = LPD_1MGeometry.from_h5_file_and_quad_positions('/home/bcalpas/machine_learning/tensorflow_keras/xfel/lpd_mar_18_axesfixed.h5', quadpos)
----> 6 geom = LPD_1MGeometry.from_h5_file_and_quad_positions('lpd_mar_18_axesfixed.h5', quadpos)
      7 
      8 

/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_data/geometry2.py in from_h5_file_and_quad_positions(cls, path, positions, unit)
    906         assert len(positions) == 4
    907         modules = []
--> 908         with h5py.File(path, 'r') as f:
    909             for Q, M in product(range(1, 5), range(1, 5)):
    910                 quad_pos = np.array(positions[Q - 1])

/software/anaconda3/5.2/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

/software/anaconda3/5.2/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     97         if swmr and swmr_support:
     98             flags |= h5f.ACC_SWMR_READ
---> 99         fid = h5f.open(name, flags, fapl=fapl)
    100     elif mode == 'r+':
    101         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

**Comment by takluyver** [comment]
If you downloaded the exact URL I posted before, it goes to a web page about the file, not the HDF5 file itself. Here's the direct download URL: https://github.com/European-XFEL/karabo_data/raw/master/docs/lpd_mar_18_axesfixed.h5

**Comment by Calpas** [comment]
- Yes, it works fine now, thank you!
- naive question: the fact that Q2M2 is showing up in Q2M4, doesn't mean that we shouldn't use that file (at least for Q2M2 part)?

**Comment by takluyver** [comment]
I'm guessing that Q2M2 wasn't present when the detector group measured it, so they put in some obviously wrong values there. Yes, it's probably a good idea not to use the Q2M2 data, which should be channel 5 in the file. One way to do this would be to [deselect](https://karabo-data.readthedocs.io/en/latest/reading_files.html#karabo_data.DataCollection.deselect) the relevant data source.

That's the only geometry file I'm aware of, so I can't offer another one which has Q2M2, but it's possible the detector group has done another one since then.

**Comment by Calpas** [comment]
Ok, thank you for your support.
Regards

**Comment by Calpas** [comment]
Dear Takluyver,
do you know who should I contact to know if a geometry file with Q2M2 is available?
Regards

**Comment by takluyver** [comment]
(Responded by email)

**Comment by Calpas** [comment]
Dear Thomas,

- ok thank you.

- Given that there are several experiments, thus detector at xfel, should we the same geometry file for all of them?

**Comment by takluyver** [comment]
No, each detector with more than one panel should have its own geometry. The LPD geometry file in that example is for the LPD detector in FXE.

For AGIPD in SPB, there are geometry files refined in CFEL beamtimes in the CrystFEL format, e.g. in [CXIDB 83](http://www.cxidb.org/id-83.html).

We hope to have a more unified mechanism for detector geometry in the future.

If you're using another multi-panel detector, you'll need to talk to the instrument scientists about its geometry.
