### ISSUE TITLE
TypeError: intersect1d() got an unexpected keyword argument 'return_indices'

### ISSUE THREAD

**Issue by Calpas** [European-XFEL/karabo_data#126]
Dear experts,
I run the command (1) which give me (2). But then running (3) give me the error message (4). Do see what is wrong?
Regards

(1)
run = run.select_trains(by_index[:10])
run.instrument_sources

(2)
frozenset({'SPB_DET_AGIPD1M-1/DET/0CH0:xtdf',
           'SPB_DET_AGIPD1M-1/DET/10CH0:xtdf',
           ...
           'SPB_DET_AGIPD1M-1/DET/9CH0:xtdf'})

(3)
data_module0 = run.get_array('SPB_DET_AGIPD1M-1/DET/0CH0:xtdf', 'image.data')

(4)
TypeError                                 Traceback (most recent call last)
<ipython-input-35-b8056678b051> in <module>()
      1 
----> 2 data_module0 = run.get_array('SPB_DET_AGIPD1M-1/DET/0CH0:xtdf', 'image.data')
      3 
      4 #data_module0.shape

/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_data/reader.py in get_array(self, source, key, extra_dims, roi)
    546         seq_arrays = []
    547 
--> 548         for chunk in self._find_data_chunks(source, key):
    549             trainids = self._expand_trainids(chunk.counts, chunk.train_ids)
    550 

/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_data/reader.py in _find_data_chunks(self, source, key)
    791         for file in self._source_index[source]:
    792             trains_of_interest, train_ixs, _ = np.intersect1d(
--> 793                 file.train_ids, self.train_ids, return_indices=True
    794             )
    795             if trains_of_interest.size == 0:

TypeError: intersect1d() got an unexpected keyword argument 'return_indices'

**Comment by takluyver** [comment]
I don't think you're doing anything wrong, but we've used something which requires a relatively new version of numpy (1.15), and it seems that the version on Maxwell is slightly too old (1.14.3).

If you're doing this with SSH to Maxwell, you can use our Anaconda installation by running `module load exfel exfel_anaconda3`. If you're using [max-jhub.desy.de](https://max-jhub.desy.de/), you can run that command in a terminal, and then there should be an 'XFEL' kernel available in the notebook menus.

**Comment by Calpas** [comment]
I'm using maxwell jupyterHub. Yes, it's working fine with 'xfel' kernel. Does it mean that I should use 'xfel' kernel to avoid troubles?

**Comment by takluyver** [comment]
For the moment, that's probably necessary. Sorry, this was an oversight on our part; we want it to work with the default Python on Maxwell as well.

**Comment by Calpas** [comment]
Ok, thank you for your answer.
Regards

**Comment by takluyver** [comment]
Opened PR #127 to fix this.
