### ISSUE TITLE
Peak search in xfel data

### ISSUE THREAD

**Issue by Calpas** [European-XFEL/karabo_data#137]
Dear experts,
- thank you for the tutorials which help understand how to access and plot the data.
- Once that is done, I wonder how can we search for peaks? 
- I know that it is based on cheetah but is there a simplify interface like crystfel at xfel to do that?
- I would like to the see images with circles on top which indicate the peaks found.
Regards

**Comment by takluyver** [comment]
We're aiming to integrate existing tools like CrystFEL rather than write our own code for things like peak finding. We're working on wrapping CrystFEL, but as far as I know it's not yet ready for users.

**Comment by Calpas** [comment]
Dear Takluyver,
ok, thank you for your answer.
Regards
