### ISSUE TITLE
Identify problematic pixel

### ISSUE THREAD

**Issue by Calpas** [European-XFEL/karabo_data#143]
Dear experts,
in an image like this (1) I guess that the yellow areas are hot or saturated... pixels. I wonder from which pixel value can we say that it's a problematic pixel?
Regards

(1)
![image](https://user-images.githubusercontent.com/6793399/55612010-7cf2d000-5787-11e9-8f68-b07e063b5775.png)

**Comment by takluyver** [comment]
There's a mask available in the calibrated data files, which should contain 0 for good pixels and other values for different kinds of bad pixel.

It's also possible for data to be recorded when the detector hardware isn't fully set up, and in this case you'll see essentially random data.

If you need more detail, or the mask isn't covering some pixels you think it should, you'll need to talk to the instrument scientists or the detector group.

**Comment by takluyver** [comment]
You can also clip extreme values out of the data, but I think what counts as extreme has to depend on the experiment and what you're doing with the data. I can't say what a sensible maximum is - but people who understand AGIPD better might be able to give you some idea.

**Comment by Calpas** [comment]
Dear Takluyver,
ok, thank you for your answer.
Regards
