### ISSUE TITLE
karabo_data not working in the default environment on maxwell

### ISSUE THREAD

**Issue by skuschel** [European-XFEL/karabo_data#153]
When I log into the maxwell cluster via jupyter and choose the environment `python 3`, the following lines of code produce an error:
```
import karabo_data
run = karabo_data.RunDirectory('/gpfs/exfel/exp/SQS/201921/p002430/raw/r0097')
run.get_array('SQS_DPU_LIC/CAM/YAG_UPSTR:daqOutput', 'data.image.pixels')
```
The error message is:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-8383a9cb7a2b> in <module>()
      1 import karabo_data
      2 run = karabo_data.RunDirectory('/gpfs/exfel/exp/SQS/201921/p002430/raw/r0097')
----> 3 run.get_array('SQS_DPU_LIC/CAM/YAG_UPSTR:daqOutput', 'data.image.pixels')

/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_data/reader.py in get_array(self, source, key, extra_dims, roi)
    546         seq_arrays = []
    547 
--> 548         for chunk in self._find_data_chunks(source, key):
    549             trainids = self._expand_trainids(chunk.counts, chunk.train_ids)
    550 

/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_data/reader.py in _find_data_chunks(self, source, key)
    791         for file in self._source_index[source]:
    792             trains_of_interest, train_ixs, _ = np.intersect1d(
--> 793                 file.train_ids, self.train_ids, return_indices=True
    794             )
    795             if trains_of_interest.size == 0:

TypeError: intersect1d() got an unexpected keyword argument 'return_indices'
```

I do have permission to access this run and the code has worked in a (strongly self configured) python environmen of a colleague. My feeling is that the installed numpy has to be updated? You can also call or visit me in the SQS control room.

Thank you
Stephan

**Comment by takluyver** [comment]
Yep, sorry. We unwittingly added something which relied on a newer version of numpy. We've addressed this in a release soon afterwards, but the main Anaconda installation on Maxwell still has the old version. We'll ask for it to be updated.

In the meantime, we've provided an Anaconda installation; if you run `module load exfel exfel_anaconda3` in a terminal, it should create an 'xfel' kernel for you to use in Jupyter.

**Comment by skuschel** [comment]
That worked! Thanks a lot!

**Comment by takluyver** [comment]
No problem. I'll leave this open until it gets updated in the main Anaconda installation, because it should be usable however it's provided.

**Comment by takluyver** [comment]
It's been upgraded in the main Anaconda installation on Maxwell, so hopefully that the last time anyone needs to run into this problem. :-)
