### ISSUE TITLE
Virtual dataset from Detector components skips missing modules

### ISSUE THREAD

**Issue by ebadkamil** [European-XFEL/karabo_data#172]
Creating virtual Data set using `write_virtual_cxi` leads to ndarray with shapes
(pulses, modules, py, px) which is perfect. However when Martin produce geometry file in crystfel format from xfel format it has information about all 16 modules. This virtual dataset then may lead to problem with crystfel because the missing modules will not be available in one big NDarray. 

```
In [55]: from karabo_data.components import LPD1M                                                                                   

In [56]: from karabo_data import RunDirectory, by_index, by_id                                                                      

In [57]: r =  RunDirectory("/gpfs/exfel/exp/XMPL/201750/p700000/proc/r0007")                                                        

In [58]: s = r.select_trains(by_id[1487289920:1487289921])                                                                          

In [59]: lpd = LPD1M(s)                                                                                                             

In [60]: lpd.write_virtual_cxi('lpd.cxi')                                                                                           

In [61]: from h5py import File                                                                                                      

In [62]: f = File('lpd.cxi')                                                                                                        

In [63]: f['entry_1/data_1/data'].shape                                                                                             
Out[63]: (30, 13, 256, 256)
```

**Comment by takluyver** [comment]
Thanks. I think it should have 16 in the modules dimension even if some of them are missing. I'll try to figure out where it's going wrong.

**Comment by ebadkamil** [comment]
Thanks Thomas

**Comment by takluyver** [comment]
I've just remembered that there is a `module_identifier` dataset in the CXI files, which should give the module number for each slice in the relevant dimension. So it's still possible for tools to correctly interpret the data in a CXI file.

Since the virtual dataset shouldn't need any extra space for the empty parts, I'll make it always have space for 16 modules so it's easier to interpret.
