### ISSUE TITLE
Assemble detector modules without copying them into a 'stack' array

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo_data#188]
From discussion relating to KaraboFAI: if you want to load data from AGIPD/LPD/DSSC and assemble it, it currently gets copied twice in memory:

individual module arrays -> stacked array -> assembled image

The first of these copies should be unnecessary. There are two basic schemes for how we could avoid it:

- Make a 'virtual' stack, e.g. a list of arrays, to represent the data without copying. We don't need to do any maths between the modules, so they don't need to be in a single array.
- Read the data directly into slices of the stacked array, so we don't allocate individual arrays for each module.

**Comment by zhujun98** [comment]
I would go for the first method and make a `StackedData` class which has several methods to provide the necessary `np.array` interface, e.g. shape property:
1. The stacked data provides the similar interface as the data from the calibration pipeline, although one needs to move the axis twice for LPD and DSSC. Therefore, it is good to 'keep' it;
2. Depending on the level of backward compatibility you want to have, there is a few options to make the new `stack_detector_data` function. No matter what, you do not need to touch the method `position_modules_fast` which is used for assembling.

**Comment by takluyver** [comment]
PR #196 is an initial attempt at implementing option 1.

**Comment by takluyver** [comment]
Done in #196.
