### ISSUE TITLE
More control of image parameters in geometry.plot_data_fast()

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo_data#204]
There are various options to `imshow()` which people want to use, e.g. `vmin` and `vmax` which are similar to `np.clip()`, and `norm` which allows the colour scale to be log normalised. Not being able to use these with `plot_data_fast()`, people assemble the array and `imshow()` it, which is inferior (IMO) for things like axis labels and representing NaN.

This could be resolved by accepting `**kwargs` and passing them through to `imshow()`, or an `imshow_kwargs` dictionary argument.

It would also be useful to have a colour bar alongside these plots.

**Comment by antarcticrainforest** [comment]
That's a good point. Since I've just learned that the computing cluster here is on maintenance and I don't have anything better to do I'll look into that.

**Comment by takluyver** [comment]
Cool, go for it. If you finish that before your cluster comes back, there are also a couple of PRs open on geoAssembler you could look at. Although maybe other people should review them to get used to that code.

**Comment by takluyver** [comment]
Closed by #205.
