### ISSUE TITLE
Couldn't open file: file.cxi

### ISSUE THREAD

**Issue by Calpas** [European-XFEL/karabo_data#223]
Dear experts,
I run (1) but I when I run (2), I got this error message (3). I already run on these files successfully 2 months ago. Do you see why it can't open the file?
Regards

(1)
/gpfs/exfel/sw/software/hdf5-virtualise/make_cxi.py /gpfs/exfel/d/proc/SPB/201801/p002120/r0096 -o r96.cxi   # OK

/gpfs/exfel/sw/software/hdf5-virtualise/access_check.py r96.cxi   # OK

(2)
 indexamajig -i r96.lst -o r96.stream -j 15 -g agipd_vds_2120_v2_120mm.geom ...

(3)
...
Indexing parameters:
                  Check unit cell parameters: on (axis combinations)
                        Check peak alignment: on
                   Refine indexing solutions: on
 Multi-lattice indexing ("delete and retry"): off
                              Retry indexing: on
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
  #000: ../../src/H5F.c line 1585 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../src/H5F.c line 1376 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../src/H5Fsuper.c line 353 in H5F_super_read(): unable to load superblock
    major: Object cache
    minor: Unable to protect metadata
  #003: ../../src/H5AC.c line 1329 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #004: ../../src/H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #005: ../../src/H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #006: ../../src/H5Fsuper_cache.c line 169 in H5F_sblock_load(): bad superblock version number
    major: File accessibilty
    minor: Bad value

Couldn't open file: r96.cxi
Failed to open r96.cxi

**Comment by takluyver** [comment]
It looks like your indexamajig is using an older version of HDF5 (it says `Error detected in HDF5 (1.8.12)`). You need to build it with HDF5 1.10 or above to read the virtual datasets.

If you've compiled indexamajig yourself, hopefully you can work out how to build it with a newer HDF5. If you're using a version someone has provided on Maxwell, you could either ask them to ensure it's built with a newer HDF5, or switch to the version we provide, which is available with:

```
module load exfel exfel_crystfel/0.8.0 
```

**Comment by Calpas** [comment]
Dear TaKluyver,
thank you, it solved the problem.
Regards

**Comment by takluyver** [comment]
Great, thanks.
