### ISSUE TITLE
Remove hdf5_file_info?

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo_data#65]
I think [this function](https://github.com/European-XFEL/karabo_data/blob/70793f6168b4bb8a6683378f10c55edee42b620d/karabo_data/utils.py#L118) is now largely redundant with the `lsxfel` machinery we added later. It doesn't seem to be used anywhere else in the codebase, and the test for it is broken (it runs `euxfel_h5tool.py`, which no longer exists).

Is there any reason to keep this as a separate function? Is there any information it gives that we want to have in other places?

For each file it shows:

- Filename
- Size in MB
- Instruments
- First & last train ID
- Pulse count per train for detector files

Then for all files it shows:

- Count
- Total size in MB
- First & last trains
- Instruments

cc @fangohr @tmichela @cydanil

**Comment by tmichela** [comment]
I think that we can safely remove all of `utils.py`.

**Comment by takluyver** [comment]
I think `QuickView` and the cbf conversion functions have the potential to be useful, and we don't have similar functionality elsewhere. They have working tests as well. It costs us little to keep things if they might come in useful. But where we have duplicate functionality and a lack of effective tests, it's worth doing some cleanup.

**Comment by tmichela** [comment]
OK, then `hdf5_file_info` and `hdf5_paths` (covered by `h5glance`) can be safely removed?

**Comment by takluyver** [comment]
I think so. Though there are probably uses for a plain-text view as well as the HTML version. Maybe it should be added to h5glance.
