### ISSUE TITLE
Aligning labelled arrays will align on all (matching?) indexes

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo_data#73]
We offer the `.get_array()` method to get an xarray labelled array from the data. If you get more than one, we document how to align these by train ID using `xarray.align()`. However, I believe this aligns all indexes with matching names, including our autogenerated `dim_0` names.

This is not appropriate if the data are from different sources where those axes represent different things - e.g. XGM data has pulses on the second axis, but digitizers have tiny time slices on that axis.

Users can work around this by specifying `extra_dims` to give explicit axis labels for at least one of the distinct datasets they want to align, overriding our 'dim_0' axis names:

```python
xtd2_intensity = run.get_array('SA1_XTD2_XGM/DOOCS/MAIN:output', 'data.intensityTD', extra_dims=['pulseID'])
```

Xarray allows axes to be unnamed, which I think would avoid the problem, but when I tried, you had to name either all axes or none, so we couldn't label the train ID axis but no others.

**Comment by tmichela** [comment]
Can we force to name all axes then? or is it too restrictive?

**Comment by takluyver** [comment]
It's certainly technically possible to force naming them all. But I suspect
it's an annoyance if you don't care about this - because you're only using
one array, or using arrays from similar devices (e.g. multiple
spectrometers in the PES). And there's not always an obvious name for the
dimension, so there's a risk that people use a meaningless name like dim0
anyway.

**Comment by takluyver** [comment]
Actually, I've just tested this in a shell, and the behaviour isn't as bad as I thought. If the extra dimensions have the same size, it leaves them alone (they're already aligned). If they have different sizes, it throws an error:

```
ValueError: arguments without labels along dimension 'dim_1' cannot be aligned because they have different dimension sizes: {3, 5}
```

There are two possible ways around that:

1. If the dimensions really are different, give one of them a different name, so xarray won't try to align it. E.g. specify `run.get_array(..., extra_dims=['pulseID'])` to mark the second dimension as pulse ID.
2. If they represent the same thing, either slice them to the same size (e.g. dropping empty pulses from the XGM), or attach coordinates to the array objects so xarray can align them.

I think that's about as sensible as this can be without some way for us to get coordinates for additional dimensions.

**Comment by fangohr** [comment]
Can we have an narrated example of the behaviour somewhere?
