### ISSUE TITLE
Value Error raised in stack_detector_data

### ISSUE THREAD

**Issue by ebadkamil** [European-XFEL/karabo_data#80]
When streaming from files for "AzimuthalIntegration FXE-tool" it happens for certain TrainId that some module has 'image.data'  of shape (0,256,256) which  raises Value Error in stack_detector_data function. Should Stack_detector_data function handle modules missing data?

**Comment by takluyver** [comment]
I think it makes sense to handle that case. Do you want to work on it? (On Monday, no need to work at the weekend, of course)
