### ISSUE TITLE
select_trains() returns DataCollection that includes unselected data

### ISSUE THREAD

**Issue by CFGrote** [European-XFEL/karabo_data#83]
The issue is demonstrated in this notebook (using karabo_data v-0.2.0, but same issue in 1.0.0):

https://git.xfel.eu/gitlab/xtooldev/XTR/blob/grotec/grotec/karabo_data_issue.ipynb

It's loading a run and then creates a new DataCollection using the select_trains() method. The returned DataCollection has the correct number of trains (and trainIds). Then, I take a series with get_series(), which now includes data from unselected trains (but not all).

**Comment by takluyver** [comment]
Thanks, PR #85 should fix this.

For reference, when you saw some but not all of the trains outside your selection, it was including the entire contents of any file which contained data for your selected train IDs.

**Comment by CFGrote** [comment]
thanks, i figured.
